const REQUEST_STORIES = 'REQUEST_STORIES';
const RECEIVE_STORIES = 'RECEIVE_STORIES';

const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';

export { REQUEST_STORIES, RECEIVE_STORIES, REQUEST_COMMENTS, RECEIVE_COMMENTS };
